# Generated by Django 4.2.4 on 2023-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arbitrage",
            fields=[
                ("arbitrage_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "outcome_1_odds",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "outcome_2_odds",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "arbitrage_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "Arbitrage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bookmakers",
            fields=[
                ("bookmaker_id", models.AutoField(primary_key=True, serialize=False)),
                ("bookmaker_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Bookmakers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name1", models.CharField(max_length=255)),
                ("team_name2", models.CharField(max_length=255)),
                ("league_name", models.CharField(max_length=255, null=True)),
                ("event_date", models.DateTimeField()),
                ("found_in", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Events",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Markets",
            fields=[
                ("market_id", models.AutoField(primary_key=True, serialize=False)),
                ("market_type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Markets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Odds",
            fields=[
                ("odd_id", models.AutoField(primary_key=True, serialize=False)),
                ("option_title", models.CharField(max_length=255)),
                ("odds_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "Odds",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Urls",
            fields=[
                ("url_id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "Urls",
                "managed": False,
            },
        ),
    ]
