# Generated by Django 4.2.4 on 2023-08-15 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ArbBackend", "0002_arbitrageoutcomes"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="arbitrageoutcomes",
            table="Arbitrage_Outcomes",
        ),
    ]
