# Generated by Django 4.2.4 on 2023-08-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ArbBackend", "0003_alter_arbitrageoutcomes_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sports",
            fields=[
                ("sport_id", models.AutoField(primary_key=True, serialize=False)),
                ("sport_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "Sports",
                "managed": False,
            },
        ),
    ]
